- name: CFME | Repositories | Disable All
  command: "subscription-manager repos --disable='*'"
  become: True

- name: CFME | Repositories | Set CFME Product Version
  set_fact:
    cfme_version_product: "{{ ansible_local['cfme']['cfme_version_product'] }}"
  when: cfme_version_product is not defined

- name: CFME | Repositories | Set Required Repositories
  set_fact:
    cfme_repositories:
      - rhel-7-server-rpms
      - rhel-server-rhscl-7-rpms
      - "cf-me-{{ cfme_version_product }}-for-rhel-7-rpms"

- name: CFME | Repositories | Enable Required Repositories
  command: "subscription-manager repos --enable='{{ item }}'"
  with_items: "{{ cfme_repositories }}"
  become: True

- name: CFME | Repositories | Enable Additional Repositories
  command: "subscription-manager repos --enable='{{ item }}'"
  with_items: "{{ addiitonal_repositories }}"
  become: True
